"""Artificial intelligence prediction and autonomous decision models.

Stores temporal forecasting inference results and autonomous or advisory control actions.
"""

from datetime import datetime
from typing import TYPE_CHECKING, Any, Optional

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.auth import User
    from app.models.intersection import Intersection


class AIPrediction(Base):
    """Predictive inference result generated by forecasting models (ST-GNN / flow forecasters)."""

    __tablename__ = "ai_predictions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    intersection_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("intersections.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    prediction_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )  # congestion, flow, incident_risk
    predicted_for: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
    )
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    confidence: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    model_version: Mapped[str] = mapped_column(String(50), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # Relationships
    intersection: Mapped[Optional["Intersection"]] = relationship(
        "Intersection",
        back_populates="ai_predictions",
    )
    decisions: Mapped[list["AIDecision"]] = relationship(
        "AIDecision",
        back_populates="prediction",
    )


class AIDecision(Base):
    """Autonomous or supervisory control recommendation generated from AI predictions."""

    __tablename__ = "ai_decisions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    prediction_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("ai_predictions.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    intersection_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("intersections.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    decision_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )  # signal_timing, route_advisory, alert
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    status: Mapped[str] = mapped_column(
        String(30),
        default="proposed",
        server_default="proposed",
        nullable=False,
        index=True,
    )  # proposed, applied, reverted
    applied_by: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    rationale: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    @property
    def applied_at(self) -> Optional[datetime]:
        """Timestamp when decision was applied, stored in memory, payload, or fallback to updated_at."""
        if hasattr(self, "_applied_at"):
            return self._applied_at
        if self.status == "applied":
            if isinstance(self.payload, dict) and "applied_at" in self.payload:
                try:
                    return datetime.fromisoformat(self.payload["applied_at"])
                except Exception:
                    pass
            return self.updated_at
        return None

    @applied_at.setter
    def applied_at(self, val: Optional[datetime]) -> None:
        self._applied_at = val

    # Relationships
    prediction: Mapped[Optional["AIPrediction"]] = relationship(
        "AIPrediction",
        back_populates="decisions",
    )
    intersection: Mapped[Optional["Intersection"]] = relationship(
        "Intersection",
        back_populates="ai_decisions",
    )
    applier: Mapped[Optional["User"]] = relationship(
        "User",
        back_populates="applied_decisions",
    )
