"""Vision module for AI TrafficOS FastAPI backend.

Provides computer vision detectors, heuristic layers, traffic metrics,
multi-object tracking, congestion scoring, incident anomaly heuristics,
and database persistence pipelines.
"""

from .congestion import (
    CongestionResult,
    CongestionWeights,
    TrafficAheadResult,
    compute_congestion_score,
    detect_traffic_ahead,
    get_congestion_calculator,
)
from .detectors import (
    CorruptFrameError,
    DEFAULT_COCO_TRAFFIC_LIGHT_ID,
    EmergencyVehicleHeuristic,
    InvalidInputFrameError,
    ModelLoadError,
    SignalDetection,
    SignalStateHeuristic,
    SignalStateResult,
    TrafficSignalDetector,
    UnsupportedInputFormatError,
    VisionDetectorError,
    YoloVehicleDetector,
    detection_to_vehicle_event_create,
    get_signal_detector,
    get_vehicle_detector,
    record_signal_observation,
)
from .incidents import (
    IncidentCandidate,
    IncidentDetector,
    LaneDirectionConfig,
    StoppedVehicleHeuristic,
    WrongWayHeuristic,
    get_incident_detector,
)
from .metrics import (
    FrameMetrics,
    PolygonROI,
    calculate_lane_occupancy,
    calculate_queue_length,
    calculate_traffic_density,
    compute_frame_metrics,
    compute_vehicle_counts,
    get_metrics_calculator,
)
from .processor import (
    CorruptVideoError,
    EmptyVideoError,
    UnsupportedVideoFormatError,
    VideoFrameResult,
    VideoOpenError,
    VideoProcessingError,
    VideoProcessor,
    get_video_processor,
)
from .storage import (
    map_confidence_to_severity,
    record_congestion_observation,
    record_incident_candidate,
    record_incident_candidates,
)
from .tracking import (
    MultiObjectTracker,
    SingleFrameSpeedError,
    TrackedVehicle,
    compute_bbox_iou,
    compute_centroid,
    estimate_speed_from_history,
    get_vehicle_tracker,
)

__all__ = [
    "CongestionResult",
    "CongestionWeights",
    "CorruptFrameError",
    "CorruptVideoError",
    "DEFAULT_COCO_TRAFFIC_LIGHT_ID",
    "EmergencyVehicleHeuristic",
    "EmptyVideoError",
    "FrameMetrics",
    "IncidentCandidate",
    "IncidentDetector",
    "InvalidInputFrameError",
    "LaneDirectionConfig",
    "ModelLoadError",
    "MultiObjectTracker",
    "PolygonROI",
    "SignalDetection",
    "SignalStateHeuristic",
    "SignalStateResult",
    "SingleFrameSpeedError",
    "StoppedVehicleHeuristic",
    "TrackedVehicle",
    "TrafficAheadResult",
    "TrafficSignalDetector",
    "UnsupportedInputFormatError",
    "UnsupportedVideoFormatError",
    "VideoFrameResult",
    "VideoOpenError",
    "VideoProcessingError",
    "VideoProcessor",
    "VisionDetectorError",
    "WrongWayHeuristic",
    "YoloVehicleDetector",
    "calculate_lane_occupancy",
    "calculate_queue_length",
    "calculate_traffic_density",
    "compute_bbox_iou",
    "compute_centroid",
    "compute_congestion_score",
    "compute_frame_metrics",
    "compute_vehicle_counts",
    "detect_traffic_ahead",
    "detection_to_vehicle_event_create",
    "estimate_speed_from_history",
    "get_congestion_calculator",
    "get_incident_detector",
    "get_metrics_calculator",
    "get_signal_detector",
    "get_vehicle_detector",
    "get_vehicle_tracker",
    "get_video_processor",
    "map_confidence_to_severity",
    "record_congestion_observation",
    "record_incident_candidate",
    "record_incident_candidates",
    "record_signal_observation",
]
