"""Structured traffic control schemas and domain contracts.

CRITICAL ARCHITECTURAL SAFETY INVARIANT:
----------------------------------------
This system is strictly advisory, supervisory, and non-actuating.
All decisions emitted by this engine are recommendations (`is_recommendation=True`).
The system NEVER claims direct hardware controller actuation, overrides local
conflict monitors, or bypasses physical failsafes. All actions are submitted as
proposals requiring human supervisory approval or compliant NTCIP field translation.
"""

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import StrEnum
from typing import Any, Optional


class DecisionAction(StrEnum):
    """Enumeration of permissible advisory traffic control actions.

    Includes exactly the defined actions for signal timing adjustment,
    emergency preemption, corridor coordination, and routing advisory.
    """

    EXTEND_GREEN = "EXTEND_GREEN"
    REDUCE_GREEN = "REDUCE_GREEN"
    CHANGE_PHASE = "CHANGE_PHASE"
    PRIORITIZE_EMERGENCY = "PRIORITIZE_EMERGENCY"
    ACTIVATE_GREEN_CORRIDOR = "ACTIVATE_GREEN_CORRIDOR"
    REROUTE_TRAFFIC = "REROUTE_TRAFFIC"
    NO_ACTION = "NO_ACTION"

    def __eq__(self, other: object) -> bool:
        """Support case-insensitive equality comparisons for robust interop."""
        if isinstance(other, str):
            return self.value.upper() == other.upper()
        return super().__eq__(other)

    def __hash__(self) -> int:
        return super().__hash__()

    @classmethod
    def _missing_(cls, value: object) -> Any:
        """Allow case-insensitive resolution from string values."""
        if isinstance(value, str):
            val_upper = value.upper()
            for member in cls:
                if member.value.upper() == val_upper:
                    return member
        return super()._missing_(value)


@dataclass(frozen=True)
class TrafficState:
    """Frozen snapshot of observed physical traffic conditions at an intersection.

    Attributes:
        intersection_id: Identifier of the junction.
        vehicle_count: Total vehicular volume observed in the telemetry window.
        density: Normalized traffic density (e.g. vehicles per area or lane length).
        queue_length: Queued vehicle count or estimated stop-bar queue length.
        occupancy: Fractional occupancy [0.0, 1.0] of intersection approach zones.
        avg_speed_kmh: Observed mean vehicular velocity in km/h (strictly None if uncalibrated).
        incident_count: Count of active, non-resolved incidents at the intersection.
        active_emergency: Flag indicating active emergency vehicle transit in proximity.
        observed_signal_state: Computer vision or telemetry signal state (red, yellow, green, unknown).
        current_phase_name: Name of active signal phase (None if unsignalized or unobserved).
        current_green_elapsed_s: Elapsed green time in seconds for active phase (None if unobserved).
        telemetry_age_s: Telemetry age in seconds since sensor capture timestamp.
        source: Ingestion source identifier ('camera', 'sensor', 'manual', 'ai').
    """

    intersection_id: int
    vehicle_count: int
    density: float
    queue_length: float
    occupancy: float
    avg_speed_kmh: Optional[float] = None
    incident_count: int = 0
    active_emergency: bool = False
    observed_signal_state: Optional[str] = None
    current_phase_name: Optional[str] = None
    current_green_elapsed_s: Optional[float] = None
    telemetry_age_s: float = 0.0
    source: str = "sensor"

    def to_dict(self) -> dict[str, Any]:
        """Convert TrafficState to a JSON-serializable dictionary."""
        return asdict(self)


@dataclass
class PredictedState:
    """Predictive forecast horizon context generated by machine learning models.

    Attributes:
        congestion: Forecasted congestion metric (0-100 scale).
        volume: Forecasted vehicular volume/flow rate.
        queue_growth: Estimated rate of queue expansion or forecast queue metric.
        horizon_minutes: Prediction horizon lookahead interval in minutes (e.g., 5, 15, 30).
        model_version: Version identifier of the inference model producing the forecast.
        confidence: Prediction confidence score [0.0, 1.0].
    """

    congestion: float
    volume: float
    queue_growth: float
    horizon_minutes: int
    model_version: Optional[str] = None
    confidence: Optional[float] = None

    def to_dict(self) -> dict[str, Any]:
        """Convert PredictedState to a JSON-serializable dictionary."""
        return asdict(self)


@dataclass
class Decision:
    """Structured advisory control recommendation produced by the decision engine.

    CRITICAL ARCHITECTURAL SAFETY INVARIANT:
    `is_recommendation` is permanently True. This system NEVER claims direct hardware
    control or unmonitored field actuation.

    Attributes:
        id: Optional persistent database identifier.
        intersection_id: Identifier of the junction for which the recommendation applies.
        action: Recommended control action directive.
        current: Observed real-time traffic state at evaluation time.
        predicted: Optional predictive forecast context used during decision formulation.
        reason: Clear, human-readable operational justification explaining the recommendation.
        expected_impact: Narrative describing projected delay reduction or safety benefits.
        confidence: Algorithmic confidence score [0.0, 1.0] for the proposed action.
        affected_signal_ids: List of database signal IDs subject to timing adjustment.
        affected_route: Optional route geometry or itinerary dict for corridor or detour actions.
        model_version: Model identifier if generated from an AI pipeline.
        created_at: Generation timestamp in UTC.
        is_recommendation: Always True; advisory guarantee.
    """

    id: Optional[int] = None
    intersection_id: int = 0
    action: DecisionAction = DecisionAction.NO_ACTION
    current: TrafficState = None  # type: ignore[assignment]
    predicted: Optional[PredictedState] = None
    reason: str = ""
    expected_impact: str = ""
    confidence: Optional[float] = None
    affected_signal_ids: list[int] = field(default_factory=list)
    affected_route: Optional[dict[str, Any]] = None
    model_version: Optional[str] = None
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    is_recommendation: bool = True

    def __post_init__(self) -> None:
        """Enforce immutability of the recommendation invariant and sanitize types."""
        # Advisory guarantee: this engine NEVER actuates field hardware directly.
        object.__setattr__(self, "is_recommendation", True)

        if self.affected_signal_ids is None:
            self.affected_signal_ids = []
        if self.created_at is None:
            self.created_at = datetime.now(timezone.utc)
        elif self.created_at.tzinfo is None:
            self.created_at = self.created_at.replace(tzinfo=timezone.utc)

    def to_dict(self, exclude_id: bool = True) -> dict[str, Any]:
        """Convert Decision to a JSON-serializable dictionary suitable for JSONB storage."""
        data: dict[str, Any] = {
            "intersection_id": self.intersection_id,
            "action": self.action.value,
            "current": self.current.to_dict() if hasattr(self.current, "to_dict") else asdict(self.current),
            "predicted": (
                self.predicted.to_dict()
                if hasattr(self.predicted, "to_dict")
                else (asdict(self.predicted) if self.predicted is not None else None)
            ),
            "reason": self.reason,
            "expected_impact": self.expected_impact,
            "confidence": self.confidence,
            "affected_signal_ids": list(self.affected_signal_ids),
            "affected_route": self.affected_route,
            "model_version": self.model_version,
            "created_at": self.created_at.isoformat(),
            "is_recommendation": True,
        }
        if not exclude_id and self.id is not None:
            data["id"] = self.id
        return data
