"""Pydantic schemas package."""

from app.schemas.ai import (
    AIDecisionCreate,
    AIDecisionResponse,
    AIDecisionUpdate,
    AIPredictionCreate,
    AIPredictionResponse,
    PaginatedAIDecisions,
    PaginatedAIPredictions,
)
from app.schemas.analytics import (
    CongestionHotspotResponse,
    IncidentsSummaryResponse,
    TrafficSummaryBucket,
)
from app.schemas.audit import (
    AuditLogResponse,
    PaginatedAuditLogs,
)
from app.schemas.auth import (
    LoginRequest,
    RefreshRequest,
    RegisterRequest,
    TokenResponse,
)
from app.schemas.forecasting import (
    ModelVersionInfo,
    PredictBatchResponse,
    PredictionResult,
    PredictRequest,
    TrainRequest,
)
from app.schemas.emergency import (
    EmergencyEventCreate,
    EmergencyEventResponse,
    EmergencyEventUpdate,
    PaginatedEmergencyEvents,
)
from app.schemas.incident import (
    IncidentCreate,
    IncidentResponse,
    IncidentUpdate,
    PaginatedIncidents,
)
from app.schemas.intersection import (
    IntersectionCreate,
    IntersectionResponse,
    IntersectionUpdate,
    PaginatedIntersections,
)
from app.schemas.lane import (
    LaneCreate,
    LaneResponse,
    LaneUpdate,
    PaginatedLanes,
)
from app.schemas.notification import (
    NotificationBroadcastCreate,
    NotificationCreate,
    NotificationReadUpdate,
    NotificationResponse,
    PaginatedNotifications,
)
from app.schemas.road import (
    PaginatedRoads,
    RoadCreate,
    RoadResponse,
    RoadUpdate,
)
from app.schemas.routing import (
    CongestionRankingItem,
    DispatchNextResponse,
    GraphStatsResponse,
    GreenCorridorRequest,
    GreenCorridorResponse,
    RouteEdgeResponse,
    RouteRequest,
    RouteResponse,
    SignalActionResponse,
    TelemetryFlushResponse,
    TelemetryIngestItem,
    TelemetryIngestResponse,
)
from app.schemas.signal import (
    PaginatedSignals,
    SignalCreate,
    SignalObservationUpdate,
    SignalOverrideRequest,
    SignalPhaseCreate,
    SignalPhaseResponse,
    SignalPhaseUpdate,
    SignalResponse,
    SignalUpdate,
)
from app.schemas.traffic_record import (
    PaginatedTrafficRecords,
    TrafficRecordBatchCreate,
    TrafficRecordBatchResponse,
    TrafficRecordCreate,
    TrafficRecordResponse,
)
from app.schemas.user import (
    PaginatedUsers,
    UserCreate,
    UserResponse,
    UserUpdate,
)
from app.schemas.vehicle_event import (
    PaginatedVehicleEvents,
    VehicleEventBatchCreate,
    VehicleEventBatchResponse,
    VehicleEventCreate,
    VehicleEventResponse,
)
from app.schemas.vision import (
    DetectionSummaryItem,
    ImageAnalysisResponse,
    PaginatedSignalObservations,
    SignalObservationItem,
    SignalObservationResult,
    VideoAnalysisResponse,
)

__all__ = [
    "DetectionSummaryItem",
    "ImageAnalysisResponse",
    "PaginatedSignalObservations",
    "SignalObservationItem",
    "SignalObservationResult",
    "VideoAnalysisResponse",
    "RegisterRequest",
    "LoginRequest",
    "TokenResponse",
    "RefreshRequest",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "PaginatedUsers",
    "RoadCreate",
    "RoadUpdate",
    "RoadResponse",
    "PaginatedRoads",
    "LaneCreate",
    "LaneUpdate",
    "LaneResponse",
    "PaginatedLanes",
    "IntersectionCreate",
    "IntersectionUpdate",
    "IntersectionResponse",
    "PaginatedIntersections",
    "SignalCreate",
    "SignalUpdate",
    "SignalObservationUpdate",
    "SignalResponse",

    "PaginatedSignals",
    "SignalPhaseCreate",
    "SignalPhaseUpdate",
    "SignalPhaseResponse",
    "SignalOverrideRequest",
    "VehicleEventCreate",
    "VehicleEventBatchCreate",
    "VehicleEventBatchResponse",
    "VehicleEventResponse",
    "PaginatedVehicleEvents",
    "IncidentCreate",
    "IncidentUpdate",
    "IncidentResponse",
    "PaginatedIncidents",
    "EmergencyEventCreate",
    "EmergencyEventUpdate",
    "EmergencyEventResponse",
    "PaginatedEmergencyEvents",
    "NotificationCreate",
    "NotificationBroadcastCreate",
    "NotificationReadUpdate",
    "NotificationResponse",
    "PaginatedNotifications",
    "TrafficRecordCreate",
    "TrafficRecordBatchCreate",
    "TrafficRecordBatchResponse",
    "TrafficRecordResponse",
    "PaginatedTrafficRecords",
    "AIPredictionCreate",
    "AIPredictionResponse",
    "PaginatedAIPredictions",
    "AIDecisionCreate",
    "AIDecisionUpdate",
    "AIDecisionResponse",
    "PaginatedAIDecisions",
    "TrafficSummaryBucket",
    "IncidentsSummaryResponse",
    "CongestionHotspotResponse",
    "AuditLogResponse",
    "PaginatedAuditLogs",
    "RouteRequest",
    "RouteEdgeResponse",
    "RouteResponse",
    "GreenCorridorRequest",
    "SignalActionResponse",
    "GreenCorridorResponse",
    "CongestionRankingItem",
    "DispatchNextResponse",
    "TelemetryIngestItem",
    "TelemetryIngestResponse",
    "TelemetryFlushResponse",
    "GraphStatsResponse",
    "TrainRequest",
    "PredictRequest",
    "PredictionResult",
    "PredictBatchResponse",
    "ModelVersionInfo",
]

