"""Pydantic schemas for intelligent traffic control endpoints (Phase 6).

Defines request/response contracts for supervisory recommendations, queue-proportional
signal optimization, macroscopic simulation, emergency preemption, corridor advisory,
and junction control status inspection.
"""

from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field


# ==============================================================================
# 1. State & Recommendation Schemas
# ==============================================================================


class TrafficStateResponse(BaseModel):
    """Snapshot of observed physical traffic conditions at an intersection."""

    model_config = ConfigDict(from_attributes=True)

    intersection_id: int = Field(..., description="Junction identifier")
    vehicle_count: int = Field(..., description="Observed vehicular volume")
    density: float = Field(..., description="Approach density")
    queue_length: float = Field(..., description="Stop-bar queue length")
    occupancy: float = Field(..., description="Approach zone occupancy [0.0, 1.0]")
    avg_speed_kmh: Optional[float] = Field(None, description="Average speed in km/h")
    incident_count: int = Field(0, description="Active non-resolved incidents")
    active_emergency: bool = Field(False, description="Active emergency vehicle presence")
    observed_signal_state: Optional[str] = Field(None, description="Observed optical signal indication")
    current_phase_name: Optional[str] = Field(None, description="Active signal phase name")
    current_green_elapsed_s: Optional[float] = Field(None, description="Elapsed green interval seconds")
    telemetry_age_s: float = Field(0.0, description="Telemetry age in seconds")
    source: str = Field("sensor", description="Data ingestion source")


class PredictedStateResponse(BaseModel):
    """Predictive forecast horizon context generated by ML pipeline."""

    model_config = ConfigDict(from_attributes=True)

    congestion: float = Field(..., description="Forecast congestion metric [0-100]")
    volume: float = Field(..., description="Forecast vehicular volume")
    queue_growth: float = Field(..., description="Forecast queue growth rate")
    horizon_minutes: int = Field(..., description="Prediction horizon in minutes")
    model_version: Optional[str] = Field(None, description="Model version producing forecast")
    confidence: Optional[float] = Field(None, description="Prediction confidence [0.0, 1.0]")


class RecommendationRequest(BaseModel):
    """Request payload to formulate an advisory control recommendation."""

    intersection_id: int = Field(..., description="Target intersection identifier")


class DecisionResponse(BaseModel):
    """Structured advisory control recommendation produced by the decision engine."""

    model_config = ConfigDict(from_attributes=True)

    id: Optional[int] = Field(None, description="Persisted decision record ID")
    intersection_id: int = Field(..., description="Intersection identifier")
    action: str = Field(..., description="Recommended control action directive")
    current: TrafficStateResponse = Field(..., description="Observed traffic state snapshot")
    predicted: Optional[PredictedStateResponse] = Field(None, description="Predictive forecast context")
    reason: str = Field(..., description="Operational justification")
    expected_impact: str = Field(..., description="Projected operational delay/safety impact")
    confidence: Optional[float] = Field(None, description="Algorithmic confidence score [0.0, 1.0]")
    affected_signal_ids: list[int] = Field(default_factory=list, description="IDs of affected signals")
    affected_route: Optional[dict[str, Any]] = Field(None, description="Affected route geometry or corridor metadata")
    model_version: Optional[str] = Field(None, description="AI model version if applicable")
    created_at: datetime = Field(..., description="Generation timestamp in UTC")
    is_recommendation: bool = Field(True, description="Advisory recommendation flag (permanently True)")


# ==============================================================================
# 2. Signal Timing Optimization Schemas
# ==============================================================================


class PhaseDemandInput(BaseModel):
    """Per-phase observed and predicted demand telemetry."""

    phase_id: int = Field(..., description="Signal phase identifier")
    queue_length: float = Field(..., ge=0.0, description="Observed stop-bar queue in vehicles")
    density: float = Field(..., ge=0.0, description="Approach lane density")
    flow_veh_per_min: float = Field(..., ge=0.0, description="Flow rate in vehicles per minute")
    predicted_congestion: Optional[float] = Field(None, ge=0.0, le=100.0, description="Predicted congestion metric")
    predicted_queue_growth: Optional[float] = Field(None, description="Predicted queue growth rate")
    lane_count: int = Field(1, ge=1, description="Number of approach lanes")
    is_emergency_route: bool = Field(False, description="Phase belongs to active emergency corridor")


class CycleConfigInput(BaseModel):
    """Operational cycle timing boundaries and transition clearance intervals."""

    min_green_s: float = Field(7.0, gt=0.0, description="Statutory minimum green in seconds")
    max_green_s: float = Field(60.0, gt=0.0, description="Maximum permissible green in seconds")
    yellow_s: float = Field(3.0, ge=0.0, description="Yellow clearance change interval in seconds")
    all_red_s: float = Field(2.0, ge=0.0, description="All-red clearance interval in seconds")


class OptimizeSignalsRequest(BaseModel):
    """Request payload for queue-proportional signal timing optimization."""

    intersection_id: int = Field(..., description="Target intersection identifier")
    phase_demands: list[PhaseDemandInput] = Field(..., min_length=1, description="Phase demand items")
    cycle_config: Optional[CycleConfigInput] = Field(None, description="Operational cycle configuration")


class OptimizeSignalsResponse(BaseModel):
    """Optimized signal timing proposal and safety validation certification."""

    model_config = ConfigDict(from_attributes=True)

    intersection_id: int = Field(..., description="Intersection identifier")
    recommended_green_s: dict[int, float] = Field(..., description="Allocated green seconds per phase_id")
    total_cycle_s: float = Field(..., description="Calculated total cycle length in seconds")
    method: str = Field(..., description="Optimization algorithm method")
    inputs_echo: dict[int, float] = Field(default_factory=dict, description="Echo of composite phase demand scores")
    computed_at: datetime = Field(..., description="Calculation timestamp in UTC")
    note: Optional[str] = Field(None, description="Diagnostic notes or justifications")
    validated: bool = Field(True, description="Safety validation pass certification")


# ==============================================================================
# 3. What-If Point-Queue Simulation Schemas
# ==============================================================================


class ApproachStateInput(BaseModel):
    """Initial physical traffic state and geometry for an approach."""

    approach_id: str = Field(..., min_length=1, description="Approach identifier")
    queue_veh: float = Field(..., ge=0.0, description="Initial stop-bar queue count in vehicles")
    arrival_rate_veh_per_min: float = Field(..., ge=0.0, description="Uniform arrival rate in veh/min")
    saturation_flow_veh_per_min: Optional[float] = Field(None, gt=0.0, description="Saturation discharge flow rate")
    lane_count: int = Field(1, ge=1, description="Number of approach lanes")
    name: Optional[str] = Field(None, description="Optional human-readable approach label")


class SignalPlanInput(BaseModel):
    """Cyclic signal timing plan and phase-to-approach assignment specification."""

    phases: dict[str, float] = Field(..., min_length=1, description="Phase green durations {phase_name: green_s}")
    phase_to_approaches: dict[str, list[str]] = Field(..., description="Phase approach mapping {phase_name: [approach_id, ...]}")
    yellow_s: float = Field(3.0, ge=0.0, description="Yellow change clearance interval in seconds")
    all_red_s: float = Field(2.0, ge=0.0, description="All-red clearance interval in seconds")


class SimulateRequest(BaseModel):
    """Request payload for comparing two candidate signal timing plans via point-queue simulation."""

    intersection_id: int = Field(..., description="Target intersection identifier")
    approaches: list[ApproachStateInput] = Field(..., min_length=1, description="Approach configurations")
    current_plan: SignalPlanInput = Field(..., description="Baseline signal timing plan")
    proposed_plan: SignalPlanInput = Field(..., description="Candidate proposed signal timing plan")
    horizon_minutes: Optional[float] = Field(15.0, gt=0.0, description="Simulation horizon lookahead in minutes")
    dt_seconds: Optional[float] = Field(5.0, gt=0.0, description="Discrete simulation time-step in seconds")


class ApproachSimulationResultResponse(BaseModel):
    """Simulated performance metrics for an individual intersection approach."""

    model_config = ConfigDict(from_attributes=True)

    approach_id: str = Field(..., description="Approach identifier")
    total_wait_veh_min: float = Field(..., description="Total waiting delay in vehicle-minutes")
    avg_queue_veh: float = Field(..., description="Time-averaged queue length in vehicles")
    max_queue_veh: float = Field(..., description="Peak queue length in vehicles")
    throughput_veh: float = Field(..., description="Total departed vehicles")
    residual_queue_veh: float = Field(..., description="Residual queue remaining at horizon end")


class SimulationResultResponse(BaseModel):
    """Aggregate simulation outcome and diagnostic breakdown for a signal plan."""

    model_config = ConfigDict(from_attributes=True)

    total_wait_veh_min: float = Field(..., description="Aggregate waiting delay across all approaches in veh*min")
    avg_queue_veh: float = Field(..., description="Mean cumulative queue length in vehicles")
    max_queue_veh: float = Field(..., description="Peak aggregate queue in vehicles")
    throughput_veh: float = Field(..., description="Total departed vehicles")
    residual_queue_veh: float = Field(..., description="Aggregate remaining queue in vehicles")
    per_approach: dict[str, ApproachSimulationResultResponse] = Field(..., description="Per-approach breakdown")
    plan_digest: str = Field(..., description="Cryptographic SHA-256 digest of signal plan")
    horizon_minutes: float = Field(..., description="Evaluation horizon in minutes")
    computed_at: datetime = Field(..., description="Simulation timestamp in UTC")
    notes: list[str] = Field(default_factory=list, description="Diagnostic notes")


class PlanComparisonResponse(BaseModel):
    """Deterministic comparison between baseline and proposed signal timing plans."""

    model_config = ConfigDict(from_attributes=True)

    current_result: SimulationResultResponse = Field(..., description="Baseline plan outcome")
    proposed_result: SimulationResultResponse = Field(..., description="Candidate plan outcome")
    delta_wait: float = Field(..., description="Wait delay delta (proposed - current) in veh*min")
    delta_avg_queue: float = Field(..., description="Average queue delta (proposed - current) in veh")
    delta_throughput: float = Field(..., description="Throughput delta (proposed - current) in veh")
    verdict: str = Field(..., description="Deterministic verdict ('proposed_better', 'current_better', 'equivalent')")


# ==============================================================================
# 4. Emergency Priority & Green Corridor Schemas
# ==============================================================================


class EmergencyPrioritizeRequest(BaseModel):
    """Request payload to prioritize an active emergency transit corridor."""

    emergency_event_id: int = Field(..., description="Emergency event identifier to prioritize")
    destination_intersection_id: int = Field(..., description="Target destination intersection identifier")


class CorridorSignalActionResponse(BaseModel):
    """Preemption or extension directive for a signal controller along the green corridor."""

    model_config = ConfigDict(from_attributes=True)

    intersection_id: int = Field(..., description="Junction identifier")
    signal_id: Optional[int] = Field(None, description="Signal controller identifier")
    action: str = Field(..., description="Signal preemption action")
    duration_seconds: float = Field(..., description="Duration in seconds")
    reason: str = Field(..., description="Operational justification")


class GreenCorridorPlanResponse(BaseModel):
    """Coordinated green wave emergency preemption corridor route and signal timing."""

    model_config = ConfigDict(from_attributes=True)

    corridor_id: str = Field(..., description="Unique corridor identifier")
    path: list[int] = Field(..., description="Ordered intersection IDs along corridor")
    signal_actions: list[CorridorSignalActionResponse] = Field(..., description="Signal actions along corridor")
    estimated_minutes: float = Field(..., description="Estimated travel time in minutes")
    from_intersection_id: int = Field(..., description="Origin intersection identifier")
    to_intersection_id: int = Field(..., description="Destination intersection identifier")


class EmergencyPrioritizeResponse(BaseModel):
    """Response payload containing activated advisory corridor and persisted decision."""

    model_config = ConfigDict(from_attributes=True)

    decision_id: int = Field(..., description="Persisted advisory decision record ID")
    corridor_plan: GreenCorridorPlanResponse = Field(..., description="Planned green wave preemption plan")
    affected_intersection_ids: list[int] = Field(..., description="Ordered intersections along corridor")
    is_recommendation: bool = Field(True, description="Advisory guarantee (permanently True)")


class EmergencyRestoreRequest(BaseModel):
    """Request payload to conclude emergency preemption and restore normal timing."""

    emergency_event_id: int = Field(..., description="Emergency event identifier to restore")


class EmergencyRestoreResponse(BaseModel):
    """Response payload for restored signal operations following emergency transit."""

    model_config = ConfigDict(from_attributes=True)

    decision_id: int = Field(..., description="Persisted NO_ACTION restore decision ID")
    emergency_event_id: int = Field(..., description="Concluded emergency event ID")
    action: str = Field("NO_ACTION", description="Restore control action")
    reason: str = Field(..., description="Operational justification")
    affected_signal_ids: list[int] = Field(default_factory=list, description="Signals returned to standard coordination")
    is_recommendation: bool = Field(True, description="Advisory guarantee (permanently True)")


class GreenCorridorRecommendRequest(BaseModel):
    """Request payload for advisory green corridor recommendation (read-only)."""

    from_intersection_id: int = Field(..., description="Origin intersection identifier")
    to_intersection_id: int = Field(..., description="Destination intersection identifier")
    emergency_speed_kmh: float = Field(60.0, ge=20.0, le=120.0, description="Cruising emergency speed in km/h")


class GreenCorridorRecommendResponse(BaseModel):
    """Read-only green corridor computation recommendation."""

    model_config = ConfigDict(from_attributes=True)

    corridor_plan: GreenCorridorPlanResponse = Field(..., description="Advisory green corridor route and signal timing")
    is_recommendation: bool = Field(True, description="Advisory guarantee (permanently True)")
    note: str = Field(
        "Advisory recommendation only; no database changes or signal actuations executed.",
        description="Operational advisory notice",
    )


# ==============================================================================
# 5. Decision Persistence & Lifecycle Schemas
# ==============================================================================


class DecisionItemResponse(BaseModel):
    """Detailed record of an advisory control decision stored in database."""

    model_config = ConfigDict(from_attributes=True)

    id: int = Field(..., description="Decision primary key ID")
    intersection_id: Optional[int] = Field(None, description="Target intersection identifier")
    decision_type: str = Field(..., description="Decision action type")
    payload: dict[str, Any] = Field(..., description="Structured decision payload JSONB")
    status: str = Field(..., description="Lifecycle status (proposed, applied, reverted)")
    applied_by: Optional[int] = Field(None, description="User ID who applied decision")
    applied_at: Optional[datetime] = Field(None, description="Timestamp when applied")
    rationale: Optional[str] = Field(None, description="Operational justification")
    created_at: datetime = Field(..., description="Creation timestamp in UTC")
    updated_at: datetime = Field(..., description="Update timestamp in UTC")


class PaginatedDecisionsResponse(BaseModel):
    """Paginated collection of advisory control decision records."""

    model_config = ConfigDict(from_attributes=True)

    items: list[DecisionItemResponse] = Field(..., description="List of decision items")
    total: int = Field(..., description="Total matching decision records")
    page: int = Field(..., description="Current page number")
    per_page: int = Field(..., description="Records per page")
    pages: int = Field(..., description="Total pages")


# ==============================================================================
# 6. Junction Control Status Schemas
# ==============================================================================


class LatestDecisionSummary(BaseModel):
    """Concise summary of the latest control decision emitted for an intersection."""

    model_config = ConfigDict(from_attributes=True)

    id: Optional[int] = Field(None, description="Decision identifier")
    action: str = Field(..., description="Advisory action directive")
    created_at: datetime = Field(..., description="Decision timestamp in UTC")
    reason: Optional[str] = Field(None, description="Decision rationale")


class LatestPredictionSummary(BaseModel):
    """Concise summary of the latest ML congestion forecast for an intersection."""

    model_config = ConfigDict(from_attributes=True)

    congestion: Optional[float] = Field(None, description="Forecast congestion metric [0-100]")
    model_version: Optional[str] = Field(None, description="Forecasting model version")
    predicted_for: Optional[datetime] = Field(None, description="Target prediction timestamp")
    confidence: Optional[float] = Field(None, description="Prediction confidence score [0.0, 1.0]")


class JunctionControlStatusResponse(BaseModel):
    """Real-time supervisory control status and health overview for an intersection."""

    model_config = ConfigDict(from_attributes=True)

    intersection_id: int = Field(..., description="Intersection identifier")
    latest_telemetry_age_s: Optional[float] = Field(None, description="Latest telemetry age in seconds")
    current_observed_signal_state: Optional[str] = Field(None, description="Current observed optical signal state")
    open_incidents_count: int = Field(0, description="Count of active non-resolved incidents")
    active_emergency: bool = Field(False, description="Flag indicating active emergency nearby")
    latest_decision: Optional[LatestDecisionSummary] = Field(None, description="Latest control decision")
    latest_prediction: Optional[LatestPredictionSummary] = Field(None, description="Latest congestion prediction")
